---
title: "Reproducible Research: Peer Assessment 1"
author: "Marco de los Santos"
output: 
  html_document:
    keep_md: true
---

## Load libraries
```{r}
library("data.table")
library(ggplot2)
```

## Loading and preprocessing the data
Unzip data to obtain a csv file.

```{r}
unzip("activity.zip",exdir = "data")
activity <- data.table::fread(input = "data/activity.csv")
```


## What is mean total number of steps taken per day?
```{r}
steps <- activity[, c(lapply(.SD, sum, na.rm = FALSE)), .SDcols = c("steps"), by = .(date)] 
head(steps, 10)
```
Histogram
```{r}
ggplot(steps, aes(x = steps)) +
    geom_histogram(fill = "steelblue", binwidth = 1000, alpha=0.6, color='black') +
    labs(title = "Daily Steps", x = "Steps", y = "Frequency")
```

mean and median of the total number of steps taken per day
```{r}
steps[, .(mean = mean(steps, na.rm = TRUE), median = median(steps, na.rm = TRUE))]
```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
